baseURL = "https://COSMOSPRO.github.io/tech_blog/"
languageCode = "zh-cn"
title = "tech_blog"
theme = "ananke"
defaultContentLanguage = "zh"

[params]
  description = "COSMOSPRO 的技术博客"
  author = "COSMOSPRO"
  mainSections = ["posts"]
  recent_posts_number = 10

  [params.ananke]
    show_recent_posts = true
    text_color = "mid-gray"
    content_alignment = "left"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
